#!/bin/bash

#version:0.1

#Activer EPEL 
yum -y install epel-release

#Activer collection de logiciels
yum -y install centos-release-scl centos-release-scl-rh

#AWX Repo 
yum install -y wget
wget -O /etc/yum.repos.d/ansible-awx.repo https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo


#RabbitMQ and Erlang 
echo "[bintraybintray-rabbitmq-rpm] 
name=bintray-rabbitmq-rpm 
baseurl=https://dl.bintray.com/rabbitmq/rpm/rabbitmq-server/v3.7.x/el/7/
gpgcheck=0 
repo_gpgcheck=0 
enabled=1" > /etc/yum.repos.d/rabbitmq.repo


#Installer RabbitMQ
yum -y install rabbitmq-server

#Installer PostgreSQL et Memcached
Install PostgreSQL and memcached

#Installer Install NGINX 
yum -y install nginx

# Installer les dependances Pythons
yum -y install rh-python36
yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*

yum install -y ansible-awx


#Initialize DB
scl enable rh-postgresql10 "postgresql-setup initdb"

#Lancer: Postgresql Database
systemctl start rh-postgresql10-postgresql.service

#Lancer RabbitMQ
systemctl start rabbitmq-server

#Creer un utilisateur awx et une base awx
scl enable rh-postgresql10 "su postgres -c \"createuser -S awx\""
scl enable rh-postgresql10 "su postgres -c \"createdb -O awx awx\""

#Importer les datas :
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"

#Configuration initial de AWX :
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage shell"
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage create_preload_data" # Optional Sample Configuration
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage provision_instance --hostname=$(hostname)"
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage register_queue --queuename=tower --hostnames=$(hostname)"

#Configuration de NGINX proxy :

wget -O /etc/nginx/nginx.conf https://raw.githubusercontent.com/MrMEEE/awx-build/master/nginx.conf

#Lancer les services
systemctl start awx

#Autoriser les services au demarrage
systemctl enable awx

